// This file is generated by Prismic local builder. Update with care!

export { default as CategoryPreviewWithImageBackgrounds } from './CategoryPreviewWithImageBackgrounds'
export { default as CategoryPreviewWithScrollingCards } from './CategoryPreviewWithScrollingCards'
export { default as HeroBanner } from './HeroBanner'
export { default as ProductFeaturesWithWideImages } from './ProductFeaturesWithWideImages'
export { default as ProductListWithCta } from './ProductListWithCta'
export { default as ProductOverviewWithImageGrid } from './ProductOverviewWithImageGrid'
export { default as PromoSectionFadingBackgroundTestimonials } from './PromoSectionFadingBackgroundTestimonials'
export { default as PromoSectionFullWidthWithOverlappingImageTiles } from './PromoSectionFullWidthWithOverlappingImageTiles'
export { default as PromoSectionImageTiles } from './PromoSectionImageTiles'
export { default as PromoSectionWithBackgroundImage } from './PromoSectionWithBackgroundImage'

import { default as PromoSectionWithBackgroundImage} from './PromoSectionWithBackgroundImage'
import { default as CategoryPreviewWithImageBackgrounds } from './CategoryPreviewWithImageBackgrounds'
import { default as CategoryPreviewWithScrollingCards } from './CategoryPreviewWithScrollingCards'
import { default as HeroBanner } from './HeroBanner'
import { default as ProductFeaturesWithWideImages } from './ProductFeaturesWithWideImages'
import { default as ProductListWithCta } from './ProductListWithCta'
import { default as ProductOverviewWithImageGrid } from './ProductOverviewWithImageGrid'
import { default as PromoSectionFadingBackgroundTestimonials } from './PromoSectionFadingBackgroundTestimonials'
import { default as PromoSectionFullWidthWithOverlappingImageTiles } from './PromoSectionFullWidthWithOverlappingImageTiles'
import { default as PromoSectionImageTiles } from './PromoSectionImageTiles'

export const components = {
    promo_section_with_background_image: PromoSectionWithBackgroundImage,
    category_preview_with_image_backgrounds: CategoryPreviewWithImageBackgrounds,
    category_preview_with_scrolling_cards: CategoryPreviewWithScrollingCards,
    hero_banner: HeroBanner,
    product_features_with_wide_images: ProductFeaturesWithWideImages,
    product_list_with_cta: ProductListWithCta,
    product_overview_with_image_grid: ProductOverviewWithImageGrid,
    promo_section_fading_background_testimonials: PromoSectionFadingBackgroundTestimonials,
    promo_section_full_width_with_overlapping_image_tiles: PromoSectionFullWidthWithOverlappingImageTiles,
    promo_section_image_tiles: PromoSectionImageTiles,
}